In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"/content/test.csv")
df.head(10)
df.shape
df.describe()
df = df.dropna(axis = 0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4434 entries, 12 to 4797
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       4434 non-null   float64
 1   High       4434 non-null   float64
 2   Low        4434 non-null   float64
 3   Close      4434 non-null   float64
 4   Inflation  4434 non-null   float64
 5   country    4434 non-null   object
 6   ISO3       4434 non-null   object
 7   date       4434 non-null   object
dtypes: float64(5), object(3)
memory usage: 311.8+ KB

In [4]:
from datetime import datetime
x = df['date']
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4434 entries, 12 to 4797
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       4434 non-null   float64
 1   High       4434 non-null   float64
 2   Low        4434 non-null   float64
 3   Close      4434 non-null   float64
 4   Inflation  4434 non-null   float64
 5   country    4434 non-null   object
 6   ISO3       4434 non-null   object
 7   date       4434 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(5), object(2)
memory usage: 311.8+ KB

In [5]:
df = df.drop(['ISO3'], axis=1)
df

      Open  High   Low  Close  Inflation      country       date
12    0.74  0.75  0.73   0.75      41.18  Afghanistan 2008-01-01
13    0.78  0.79  0.77   0.77      44.45  Afghanistan 2008-02-01
14    0.79  0.82  0.78   0.82      53.62  Afghanistan 2008-03-01
15    0.85  0.92  0.84   0.92      66.52  Afghanistan 2008-04-01
16    0.96  1.02  0.94   1.02      77.51  Afghanistan 2008-05-01
...    ...   ...   ...    ...        ...          ...        ...
4793  2.74  2.78  2.70   2.75      -0.28  Yemen, Rep. 2023-06-01
4794  2.79  2.83  2.75   2.81      -1.85  Yemen, Rep. 2023-07-01
4795  2.85  2.89  2.81   2.83      -3.17  Yemen, Rep. 2023-08-01
4796  2.86  2.97  2.82   2.97       1.68  Yemen, Rep. 2023-09-01
4797  3.06  3.11  2.98   2.98       3.76  Yemen, Rep. 2023-10-01

[4434 rows x 7 columns]

In [6]:
import pandas as pd
encoded_df = pd.get_dummies(data = df, columns =['country'])
encoded_df

,Open,High,Low,Close,Inflation,date,country_Afghanistan,country_Burkina Faso,country_Burundi,country_Cameroon,...,country_Mali,country_Mozambique,country_Myanmar,country_Niger,country_Nigeria,country_Somalia,country_South Sudan,country_Sudan,country_Syrian Arab Republic,"country_Yemen, Rep."
12,0.74,0.75,0.73,0.75,41.18,2008-01-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0.78,0.79,0.77,0.77,44.45,2008-02-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0.79,0.82,0.78,0.82,53.62,2008-03-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0.85,0.92,0.84,0.92,66.52,2008-04-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0.96,1.02,0.94,1.02,77.51,2008-05-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4793,2.74,2.78,2.70,2.75,-0.28,2023-06-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4794,2.79,2.83,2.75,2.81,-1.85,2023-07-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4795,2.85,2.89,2.81,2.83,-3.17,2023-08-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4796,2.86,2.97,2.82,2.97,1.68,2023-09-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4797,3.06,3.11,2.98,2.98,3.76,2023-10-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
import pandas as pd
x_train = encoded_df.drop(labels = 'Inflation',axis = 1 )[encoded_df['date'].dt.year < 2020]
x_test = encoded_df.drop(labels = 'Inflation',axis = 1 )[encoded_df['date'].dt.year >= 2020]

y_train = encoded_df[encoded_df['date'].dt.year < 2020]['Inflation'].values
y_test = encoded_df[encoded_df['date'].dt.year >= 2020]['Inflation'].values

x_train.drop(labels = 'date',axis = True , inplace = True)
x_test.drop(labels = 'date',axis = True , inplace = True)

print(x_test)
print(x_train)
np.shape(y_train)
encoded_df

      Open  High   Low  Close  country_Afghanistan  country_Burkina Faso  \
156   1.02  1.03  1.02   1.02                    1                     0
157   1.03  1.03  1.02   1.02                    1                     0
158   1.03  1.06  1.02   1.06                    1                     0
159   1.08  1.11  1.07   1.11                    1                     0
160   1.15  1.16  1.13   1.13                    1                     0
...    ...   ...   ...    ...                  ...                   ...
4793  2.74  2.78  2.70   2.75                    0                     0
4794  2.79  2.83  2.75   2.81                    0                     0
4795  2.85  2.89  2.81   2.83                    0                     0
4796  2.86  2.97  2.82   2.97                    0                     0
4797  3.06  3.11  2.98   2.98                    0                     0

      country_Burundi  country_Cameroon  country_Central African Republic  \
156                 0                 0                                 0
157                 0                 0                                 0
158                 0                 0                                 0
159                 0                 0                                 0
160                 0                 0                                 0
...               ...               ...                               ...
4793                0                 0                                 0
4794                0                 0                                 0
4795                0                 0                                 0
4796                0                 0                                 0
4797                0                 0                                 0

      country_Chad  ...  country_Mali  country_Mozambique  country_Myanmar  \
156              0  ...             0                   0                0
157              0  ...             0                   0                0
158              0  ...             0                   0                0
159              0  ...             0                   0                0
160              0  ...             0                   0                0
...            ...  ...           ...                 ...              ...
4793             0  ...             0                   0                0
4794             0  ...             0                   0                0
4795             0  ...             0                   0                0
4796             0  ...             0                   0                0
4797             0  ...             0                   0                0

      country_Niger  country_Nigeria  country_Somalia  country_South Sudan  \
156               0                0                0                    0
157               0                0                0                    0
158               0                0                0                    0
159               0                0                0                    0
160               0                0                0                    0
...             ...              ...              ...                  ...
4793              0                0                0                    0
4794              0                0                0                    0
4795              0                0                0                    0
4796              0                0                0                    0
4797              0                0                0                    0

      country_Sudan  country_Syrian Arab Republic  country_Yemen, Rep.
156               0                             0                    0
157               0                             0                    0
158               0                             0                    0
159               0                             0                    0
160               0                             0                    0
...             ...                           ...                  ...
4793              0                             0                    1
4794              0                             0                    1
4795              0                             0                    1
4796              0                             0                    1
4797              0                             0                    1

[1150 rows x 29 columns]
      Open  High   Low  Close  country_Afghanistan  country_Burkina Faso  \
12    0.74  0.75  0.73   0.75                    1                     0
13    0.78  0.79  0.77   0.77                    1                     0
14    0.79  0.82  0.78   0.82                    1                     0
15    0.85  0.92  0.84   0.92                    1                     0
16    0.96  1.02  0.94   1.02                    1                     0
...    ...   ...   ...    ...                  ...                   ...
4747  1.33  1.37  1.30   1.37                    0                     0
4748  1.40  1.43  1.36   1.38                    0                     0
4749  1.39  1.42  1.36   1.38                    0                     0
4750  1.39  1.42  1.34   1.34                    0                     0
4751  1.33  1.36  1.30   1.33                    0                     0

      country_Burundi  country_Cameroon  country_Central African Republic  \
12                  0                 0                                 0
13                  0                 0                                 0
14                  0                 0                                 0
15                  0                 0                                 0
16                  0                 0                                 0
...               ...               ...                               ...
4747                0                 0                                 0
4748                0                 0                                 0
4749                0                 0                                 0
4750                0                 0                                 0
4751                0                 0                                 0

      country_Chad  ...  country_Mali  country_Mozambique  country_Myanmar  \
12               0  ...             0                   0                0
13               0  ...             0                   0                0
14               0  ...             0                   0                0
15               0  ...             0                   0                0
16               0  ...             0                   0                0
...            ...  ...           ...                 ...              ...
4747             0  ...             0                   0                0
4748             0  ...             0                   0                0
4749             0  ...             0                   0                0
4750             0  ...             0                   0                0
4751             0  ...             0                   0                0

      country_Niger  country_Nigeria  country_Somalia  country_South Sudan  \
12                0                0                0                    0
13                0                0                0                    0
14                0                0                0                    0
15                0                0                0                    0
16                0                0                0                    0
...             ...              ...              ...                  ...
4747              0                0                0                    0
4748              0                0                0                    0
4749              0                0                0                    0
4750              0                0                0                    0
4751              0                0                0                    0

      country_Sudan  country_Syrian Arab Republic  country_Yemen, Rep.
12                0                             0                    0
13                0                             0                    0
14                0                             0                    0
15                0                             0                    0
16                0                             0                    0
...             ...                           ...                  ...
4747              0                             0                    1
4748              0                             0                    1
4749              0                             0                    1
4750              0                             0                    1
4751              0                             0                    1

[3284 rows x 29 columns]

,Open,High,Low,Close,Inflation,date,country_Afghanistan,country_Burkina Faso,country_Burundi,country_Cameroon,...,country_Mali,country_Mozambique,country_Myanmar,country_Niger,country_Nigeria,country_Somalia,country_South Sudan,country_Sudan,country_Syrian Arab Republic,"country_Yemen, Rep."
12,0.74,0.75,0.73,0.75,41.18,2008-01-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0.78,0.79,0.77,0.77,44.45,2008-02-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0.79,0.82,0.78,0.82,53.62,2008-03-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0.85,0.92,0.84,0.92,66.52,2008-04-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0.96,1.02,0.94,1.02,77.51,2008-05-01,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4793,2.74,2.78,2.70,2.75,-0.28,2023-06-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4794,2.79,2.83,2.75,2.81,-1.85,2023-07-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4795,2.85,2.89,2.81,2.83,-3.17,2023-08-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4796,2.86,2.97,2.82,2.97,1.68,2023-09-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4797,3.06,3.11,2.98,2.98,3.76,2023-10-01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [8]:
!pip  install scikit-learn
from sklearn.linear_model import LinearRegression
linear_regressor = LinearRegression()
linear_regressor.fit(x_train,y_train)
y_pred_lr = linear_regressor.predict(x_test)
# y_pred_lr
from sklearn.metrics import mean_absolute_error as mae , mean_squared_error as mse
print("----------Linear Reggression- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_lr)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_lr)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_lr))))
print(linear_regressor.score(x_test,y_test))
print(linear_regressor.score(x_train,y_train))

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)
----------Linear Reggression- Model Evaluvation-----------
Mean Absolute Error (MAE) : 80.52148407211756
Mean Squared Error (MSE) : 145132.78800688556
Root MeanSquared Error (RMSE) : 380.9629745879323
-62.52863944316665
0.34793423519263533

In [9]:
from sklearn.tree import DecisionTreeRegressor
Decision_Regressor = DecisionTreeRegressor()
Decision_Regressor.fit(x_train,y_train)
y_pred_dr = Decision_Regressor.predict(x_test)
# y_pred_dr
print("----------Decision Tree Regressor- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_dr)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_dr)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_dr))))
print(Decision_Regressor.score(x_test,y_test))
print(Decision_Regressor.score(x_train,y_train))

----------Decision Tree Regressor- Model Evaluvation-----------
Mean Absolute Error (MAE) : 30.211940320910976
Mean Squared Error (MSE) : 2411.980887548423
Root MeanSquared Error (RMSE) : 49.11192205105012
-0.055790812353188945
0.9786584393822397

In [11]:
from sklearn.ensemble import RandomForestRegressor
Random_Regressor = RandomForestRegressor()
Random_Regressor.fit(x_train,y_train)
y_pred_rr = Decision_Regressor.predict(x_test)
y_pred_rr
print("----------Random Forest Regressor - Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_rr)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_rr)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_rr))))
print(Random_Regressor.score(x_test,y_test))
print(Random_Regressor.score(x_train,y_train))

----------Random Forest Regressor - Model Evaluvation-----------
Mean Absolute Error (MAE) : 30.211940320910976
Mean Squared Error (MSE) : 2411.980887548423
Root MeanSquared Error (RMSE) : 49.11192205105012
0.01342701202722707
0.9545378522622496

In [12]:
from sklearn.ensemble import AdaBoostRegressor
Ada_Regressor =AdaBoostRegressor(base_estimator=linear_regressor, n_estimators=1000, learning_rate=25, random_state = 42)
Ada_Regressor.fit(x_train,y_train)
y_pred_ad = Ada_Regressor.predict(x_test)
y_pred_ad
print("----------Ada Boost Regressor- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_ad)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_ad)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_ad))))
print(Ada_Regressor.score(x_test,y_test))
print(Ada_Regressor.score(x_train,y_train))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

----------Ada Boost Regressor- Model Evaluvation-----------
Mean Absolute Error (MAE) : 58.67197210234596
Mean Squared Error (MSE) : 5094.037084501791
Root MeanSquared Error (RMSE) : 71.37252331606183
-1.2298010649122277
-2.712323369092112

In [13]:
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse
import numpy as np
svm_regressor = SVR()
svm_regressor.fit(x_train, y_train)
y_pred_svm = svm_regressor.predict(x_test)
print("----------Support Vector Machine Regressor - Model Evaluation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test, y_pred_svm)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test, y_pred_svm)))
print("Root Mean Squared Error (RMSE) : {}".format(np.sqrt(mse(y_test, y_pred_svm))))
print("R² Score : {}".format(svm_regressor.score(x_test, y_test)))
print("Training R² Score : {}".format(svm_regressor.score(x_train, y_train)))

----------Support Vector Machine Regressor - Model Evaluation-----------
Mean Absolute Error (MAE) : 24.039901206981682
Mean Squared Error (MSE) : 2269.9274227368805
Root Mean Squared Error (RMSE) : 47.64375533831145
R² Score : 0.006389922073527399
Training R² Score : 0.12177972842199214

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse
import numpy as np
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=x_train.shape[1]))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='linear'))
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(x_train, y_train, epochs=50, batch_size=32, validation_data=(x_test, y_test))
y_pred_nn = model.predict(x_test).flatten()
print("----------Neural Network Regressor - Model Evaluation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test, y_pred_nn)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test, y_pred_nn)))
print("Root Mean Squared Error (RMSE) : {}".format(np.sqrt(mse(y_test, y_pred_nn))))

Epoch 1/50
103/103 [==============================] - 1s 3ms/step - loss: 892.7351 - val_loss: 3146.2769
Epoch 2/50
103/103 [==============================] - 0s 2ms/step - loss: 825.7133 - val_loss: 4605.6777
Epoch 3/50
103/103 [==============================] - 0s 1ms/step - loss: 776.1920 - val_loss: 4969.5132
Epoch 4/50
103/103 [==============================] - 0s 2ms/step - loss: 708.9252 - val_loss: 7976.6680
Epoch 5/50
103/103 [==============================] - 0s 1ms/step - loss: 646.9446 - val_loss: 14031.7100
Epoch 6/50
103/103 [==============================] - 0s 2ms/step - loss: 610.2697 - val_loss: 34346.9922
Epoch 7/50
103/103 [==============================] - 0s 2ms/step - loss: 594.9741 - val_loss: 37730.6953
Epoch 8/50
103/103 [==============================] - 0s 2ms/step - loss: 589.2831 - val_loss: 39123.1172
Epoch 9/50
103/103 [==============================] - 0s 2ms/step - loss: 583.2717 - val_loss: 43019.9961
Epoch 10/50
103/103 [==============================] - 0s 1ms/step - loss: 581.3584 - val_loss: 52993.4023
Epoch 11/50
103/103 [==============================] - 0s 1ms/step - loss: 577.9626 - val_loss: 46731.2734
Epoch 12/50
103/103 [==============================] - 0s 2ms/step - loss: 574.7875 - val_loss: 50451.6914
Epoch 13/50
103/103 [==============================] - 0s 2ms/step - loss: 573.4290 - val_loss: 50118.7891
Epoch 14/50
103/103 [==============================] - 0s 2ms/step - loss: 573.8371 - val_loss: 58925.1328
Epoch 15/50
103/103 [==============================] - 0s 2ms/step - loss: 571.7125 - val_loss: 48535.5352
Epoch 16/50
103/103 [==============================] - 0s 2ms/step - loss: 570.5742 - val_loss: 57679.4180
Epoch 17/50
103/103 [==============================] - 0s 2ms/step - loss: 570.0224 - val_loss: 54856.0234
Epoch 18/50
103/103 [==============================] - 0s 1ms/step - loss: 567.2649 - val_loss: 42555.5859
Epoch 19/50
103/103 [==============================] - 0s 2ms/step - loss: 567.1122 - val_loss: 50280.9727
Epoch 20/50
103/103 [==============================] - 0s 2ms/step - loss: 564.4117 - val_loss: 51907.3438
Epoch 21/50
103/103 [==============================] - 0s 2ms/step - loss: 567.1676 - val_loss: 50447.8906
Epoch 22/50
103/103 [==============================] - 0s 2ms/step - loss: 563.1235 - val_loss: 56269.8555
Epoch 23/50
103/103 [==============================] - 0s 2ms/step - loss: 561.1111 - val_loss: 42533.6953
Epoch 24/50
103/103 [==============================] - 0s 2ms/step - loss: 559.9079 - val_loss: 52757.4961
Epoch 25/50
103/103 [==============================] - 0s 2ms/step - loss: 558.0127 - val_loss: 43157.2305
Epoch 26/50
103/103 [==============================] - 0s 1ms/step - loss: 557.3893 - val_loss: 53501.7930
Epoch 27/50
103/103 [==============================] - 0s 2ms/step - loss: 556.8328 - val_loss: 54041.7422
Epoch 28/50
103/103 [==============================] - 0s 2ms/step - loss: 556.4771 - val_loss: 45747.0742
Epoch 29/50
103/103 [==============================] - 0s 2ms/step - loss: 552.6415 - val_loss: 49579.1914
Epoch 30/50
103/103 [==============================] - 0s 2ms/step - loss: 553.7415 - val_loss: 46539.6172
Epoch 31/50
103/103 [==============================] - 0s 2ms/step - loss: 551.1318 - val_loss: 35248.8711
Epoch 32/50
103/103 [==============================] - 0s 2ms/step - loss: 550.5201 - val_loss: 52586.7812
Epoch 33/50
103/103 [==============================] - 0s 2ms/step - loss: 548.7356 - val_loss: 40919.6680
Epoch 34/50
103/103 [==============================] - 0s 1ms/step - loss: 545.3323 - val_loss: 59300.6875
Epoch 35/50
103/103 [==============================] - 0s 1ms/step - loss: 547.9147 - val_loss: 50505.0234
Epoch 36/50
103/103 [==============================] - 0s 1ms/step - loss: 541.7363 - val_loss: 52632.3633
Epoch 37/50
103/103 [==============================] - 0s 2ms/step - loss: 543.4148 - val_loss: 51704.2383
Epoch 38/50
103/103 [==============================] - 0s 1ms/step - loss: 538.9541 - val_loss: 43704.5352
Epoch 39/50
103/103 [==============================] - 0s 2ms/step - loss: 538.4774 - val_loss: 35159.2539
Epoch 40/50
103/103 [==============================] - 0s 2ms/step - loss: 542.5933 - val_loss: 40730.4336
Epoch 41/50
103/103 [==============================] - 0s 2ms/step - loss: 534.2827 - val_loss: 57418.5820
Epoch 42/50
103/103 [==============================] - 0s 2ms/step - loss: 535.0179 - val_loss: 39930.2148
Epoch 43/50
103/103 [==============================] - 0s 2ms/step - loss: 531.0200 - val_loss: 38913.2930
Epoch 44/50
103/103 [==============================] - 0s 1ms/step - loss: 532.7467 - val_loss: 40439.1445
Epoch 45/50
103/103 [==============================] - 0s 2ms/step - loss: 528.3842 - val_loss: 39914.8320
Epoch 46/50
103/103 [==============================] - 0s 2ms/step - loss: 525.9468 - val_loss: 34699.9414
Epoch 47/50
103/103 [==============================] - 0s 1ms/step - loss: 528.2780 - val_loss: 33614.7305
Epoch 48/50
103/103 [==============================] - 0s 2ms/step - loss: 524.2615 - val_loss: 41195.9766
Epoch 49/50
103/103 [==============================] - 0s 2ms/step - loss: 521.8696 - val_loss: 42218.1914
Epoch 50/50
103/103 [==============================] - 0s 2ms/step - loss: 520.6468 - val_loss: 39241.3320
36/36 [==============================] - 0s 846us/step
----------Neural Network Regressor - Model Evaluation-----------
Mean Absolute Error (MAE) : 52.984695110995354
Mean Squared Error (MSE) : 39241.32710554128
Root Mean Squared Error (RMSE) : 198.09423794129216

In [15]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse
import numpy as np
knn_regressor = KNeighborsRegressor(n_neighbors=20)
knn_regressor.fit(x_train, y_train)
y_pred_knn = knn_regressor.predict(x_test)
print("----------K-Nearest Neighbors Regressor - Model Evaluation-----------")
print("Mean Absolute Error (MAE): {}".format(mae(y_test, y_pred_knn)))
print("Mean Squared Error (MSE): {}".format(mse(y_test, y_pred_knn)))
print("Root Mean Squared Error (RMSE): {}".format(np.sqrt(mse(y_test, y_pred_knn))))
print("R² Score : {}".format(knn_regressor.score(x_test, y_test)))
print("Training R² Score : {}".format(knn_regressor.score(x_train, y_train)))

----------K-Nearest Neighbors Regressor - Model Evaluation-----------
Mean Absolute Error (MAE): 21.382765217391306
Mean Squared Error (MSE): 1206.848040536087
Root Mean Squared Error (RMSE): 34.73971848671326
R² Score : 0.4717291999773905
Training R² Score : 0.728975521973664

In [16]:
def predict_inflation( Country = 'Mali' ,Open = 50,	High = 100, Low = 0, Close = 75):
  temp_array = list()
  if Country == 'Afghanistan':
    temp_array = temp_array + [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Burkina Faso':
    temp_array = temp_array + [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Burundi':
    temp_array = temp_array + [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Cameroon':
    temp_array = temp_array + [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Central African Republic':
    temp_array = temp_array + [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Chad':
    temp_array = temp_array + [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Congo, Dem. Rep.':
    temp_array = temp_array + [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Congo, Rep.':
    temp_array = temp_array + [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Gambia, The':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Guinea-Bissau':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Haiti':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Iraq':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Lao PDR':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Lebanon':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Liberia':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0]
  elif Country == 'Mali':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0]
  elif Country == 'Mozambique':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0]
  elif Country == 'Myanmar':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]
  elif Country == 'Niger':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0]
  elif Country == 'Nigeria':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]
  elif Country == 'Somali':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0]
  elif Country == 'South Sudan':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]
  elif Country == 'Sudan':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0]
  elif Country == 'Yemen, Rep.':
    temp_array = temp_array + [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]
  else :
    print("Invalid Country name !! ")
  temp_array =  [Open,High,Low,Close] + temp_array
  temp_array = np.array(temp_array).reshape(1,-1)
  return int(knn_regressor.predict(temp_array))

In [17]:
final_inflation = predict_inflation (Country = 'Mali' ,Open = 50,	High = 100, Low = 0, Close = 75)
print("The final predicted score (range): ({} to {})".format(final_inflation - 5, final_inflation + 5))

The final predicted score (range): (78 to 88)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [18]:
Open = float(input("Enter the opening value : "))
High = float(input("Enter the higest value : "))
Low = float(input("Enter the lowest value : "))
Close = float(input("Enter the closing value : ")
)
Country = input("Enter the Country Code  :  ")
final_inflation = predict_inflation (Country,Open,High,Low,Close)
print("The final predicted score (range): ({}to{})".format(final_inflation - 5, final_inflation + 5))

Enter the opening value : 8
Enter the higest value : 10
Enter the lowest value : 4
Enter the closing value : 6
Enter the Country Code  :  Sudan
The final predicted score (range): (78to88)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [21]:
import pickle
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(knn_regressor, file)